### ISSUE TITLE
KeyError in urllib.quote

### ISSUE THREAD

**Issue by roselone** [JohnDoee/deluge-streaming#9]
hi, click "Stream this file",  not working
KeyError: u'\u7eb3

The torrent file has **Chinese character**, maybe the reason for key error?
 
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/deluge/ui/client.py", line 504, in __call__
    return self.daemon.call(self.base, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/deluge/ui/client.py", line 457, in call
    return defer.maybeDeferred(m, *copy.deepcopy(args), **copy.deepcopy(kwargs))
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/roselone/.config/deluge/plugins/Streaming-0.5.0-py2.7.egg/streaming/core.py", line 616, in stream_torrent
    
  File "/usr/lib/python2.7/urllib.py", line 1310, in quote_plus
    return quote(s, safe)
  File "/usr/lib/python2.7/urllib.py", line 1303, in quote
    return ''.join(map(quoter, s))
exceptions.KeyError: u'\u7eb3'

```

**Comment by JohnDoee** [comment]
Thanks for reporting it.

It should work in the new version, you can find it here:
https://github.com/JohnDoee/deluge-streaming/releases/tag/0.6.1
